//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenMoon.Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityForum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunityForum()
        {
            this.CommunityCategories = new HashSet<CommunityCategory>();
        }
    
        public int ForumId { get; set; }
        public string ForumName { get; set; }
        public string ForumDisplayName { get; set; }
        public string ForumImage { get; set; }
        public int Order { get; set; }
        public bool UseTraditionalStyle { get; set; }
        public bool StaffOnly { get; set; }
        public bool Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunityCategory> CommunityCategories { get; set; }
    }
}
