//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenMoon.Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunityCategory()
        {
            this.CommunitySubCategories = new HashSet<CommunitySubCategory>();
        }
    
        public int CategoryId { get; set; }
        public int ParentForumId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDisplayName { get; set; }
        public string CategoryDescription { get; set; }
        public int Order { get; set; }
        public bool Visible { get; set; }
    
        public virtual CommunityForum CommunityForum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunitySubCategory> CommunitySubCategories { get; set; }
    }
}
