//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenMoon.Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunitySubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunitySubCategory()
        {
            this.CommunityTopics = new HashSet<CommunityTopic>();
        }
    
        public int SubCategoryId { get; set; }
        public int ParentCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryDisplayname { get; set; }
        public string SubCategoryDescription { get; set; }
        public int Order { get; set; }
        public bool Visible { get; set; }
    
        public virtual CommunityCategory CommunityCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunityTopic> CommunityTopics { get; set; }
    }
}
