//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenMoon.Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityTopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunityTopic()
        {
            this.CommunityPosts = new HashSet<CommunityPost>();
        }
    
        public int TopicId { get; set; }
        public int SubCategoryId { get; set; }
        public string TopicTitle { get; set; }
        public System.DateTime TopicDate { get; set; }
        public bool Deleted { get; set; }
        public bool Locked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunityPost> CommunityPosts { get; set; }
        public virtual CommunitySubCategory CommunitySubCategory { get; set; }
    }
}
