//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenMoon.Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityPost
    {
        public int PostId { get; set; }
        public int ParentTopicId { get; set; }
        public int UserId { get; set; }
        public string PostText { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
    
        public virtual CommunityTopic CommunityTopic { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
