//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenMoon.Library.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEV_fallencoreEntities : DbContext
    {
        public DEV_fallencoreEntities()
            : base("name=DEV_fallencoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogPost> BlogPosts { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserEmailConfirmation> UserEmailConfirmations { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserRank> UserRanks { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<BlogPostCommentReport> BlogPostCommentReports { get; set; }
        public virtual DbSet<BlogPostComment> BlogPostComments { get; set; }
        public virtual DbSet<CommunityCategory> CommunityCategories { get; set; }
        public virtual DbSet<CommunityForum> CommunityForums { get; set; }
        public virtual DbSet<CommunityPost> CommunityPosts { get; set; }
        public virtual DbSet<CommunitySubCategory> CommunitySubCategories { get; set; }
        public virtual DbSet<CommunityTopic> CommunityTopics { get; set; }
    }
}
