//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallenMoon.Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmailConfirmation
    {
        public int ConfirmationId { get; set; }
        public int UserId { get; set; }
        public string ConfirmationNumber { get; set; }
        public System.DateTime DateSent { get; set; }
        public bool Redeemed { get; set; }
        public Nullable<System.DateTime> DateRedeemed { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
